# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-04-01 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrometheusFederal',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='\u552f\u4e00\u6807\u8bc6')),
                ('name', models.CharField(max_length=100, verbose_name='\u540d\u79f0')),
                ('url', models.CharField(max_length=100, verbose_name='\u5730\u5740')),
            ],
            options={
                'db_table': 'federal',
            },
        ),
    ]
