# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-03-11 03:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrometheusTriggers',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='\u89e6\u53d1\u5668\u540d\u79f0')),
                ('expr', models.CharField(max_length=100, verbose_name='\u8868\u8fbe\u5f0f')),
                ('service', models.CharField(max_length=100, verbose_name='service\u5206\u7ec4')),
                ('for_time', models.CharField(max_length=100, verbose_name='\u6301\u7eed\u65f6\u95f4')),
                ('level', models.CharField(max_length=100, verbose_name='\u544a\u8b66\u7ea7\u522b')),
                ('summary', models.CharField(max_length=1000, verbose_name='\u544a\u8b66\u6a21\u677f')),
                ('description', models.CharField(max_length=1000, verbose_name='\u63cf\u8ff0')),
                ('hostid', models.CharField(max_length=100, verbose_name='\u6240\u5c5e\u4e3b\u673a')),
            ],
            options={
                'db_table': 'triggers',
            },
        ),
    ]
