# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-03-28 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrometheusUser',
            fields=[
                ('uid', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='\u552f\u4e00\u6807\u8bc6')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='\u540d\u79f0')),
                ('passwd', models.CharField(max_length=100, verbose_name='\u5bc6\u7801')),
                ('status', models.CharField(max_length=100, verbose_name='\u72b6\u6001')),
            ],
            options={
                'db_table': 'userconfig',
            },
        ),
    ]
