# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-03-14 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrometheusApplication',
            fields=[
                ('aid', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='\u552f\u4e00\u6807\u8bc6')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='\u89e6\u53d1\u5668\u540d\u79f0')),
            ],
            options={
                'db_table': 'application',
            },
        ),
        migrations.CreateModel(
            name='PrometheusRules',
            fields=[
                ('rid', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='\u552f\u4e00\u6807\u8bc6')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='\u89e6\u53d1\u5668\u540d\u79f0')),
                ('service', models.CharField(max_length=100, verbose_name='\u670d\u52a1')),
                ('fortime', models.CharField(max_length=100, verbose_name='\u6301\u7eed\u65f6\u95f4')),
                ('model', models.CharField(max_length=1000, verbose_name='\u6a21\u677f')),
                ('description', models.CharField(max_length=1000, verbose_name='\u63cf\u8ff0')),
                ('level', models.CharField(max_length=100, verbose_name='\u544a\u8b66\u7b49\u7ea7')),
                ('application', models.CharField(max_length=100, verbose_name='\u5e94\u7528\u96c6')),
                ('expr', models.CharField(max_length=1000, verbose_name='\u8868\u8fbe\u5f0f')),
                ('hid', models.CharField(max_length=100, verbose_name='\u4e3b\u673aid')),
                ('status', models.CharField(max_length=100, verbose_name='\u72b6\u6001')),
            ],
            options={
                'db_table': 'rules',
            },
        ),
        migrations.CreateModel(
            name='PrometheusRulesModel',
            fields=[
                ('rid', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='\u552f\u4e00\u6807\u8bc6')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='\u89e6\u53d1\u5668\u540d\u79f0')),
                ('service', models.CharField(max_length=100, verbose_name='\u670d\u52a1')),
                ('fortime', models.CharField(max_length=100, verbose_name='\u6301\u7eed\u65f6\u95f4')),
                ('model', models.CharField(max_length=1000, verbose_name='\u6a21\u677f')),
                ('description', models.CharField(max_length=1000, verbose_name='\u63cf\u8ff0')),
                ('level', models.CharField(max_length=100, verbose_name='\u544a\u8b66\u7b49\u7ea7')),
                ('application', models.CharField(max_length=100, verbose_name='\u5e94\u7528\u96c6')),
                ('expr', models.CharField(max_length=1000, verbose_name='\u8868\u8fbe\u5f0f')),
            ],
            options={
                'db_table': 'rules_model',
            },
        ),
    ]
