# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-03-19 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addrules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prometheusrules',
            name='modelid',
            field=models.CharField(default=1, max_length=100, verbose_name='\u6a21\u677fid'),
            preserve_default=False,
        ),
    ]
