# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-03-28 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrometheusAlarm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, verbose_name='\u544a\u8b66\u65b9\u5f0f')),
                ('url', models.CharField(max_length=1000, verbose_name='\u5bf9\u63a5\u5730\u5740')),
                ('name', models.CharField(max_length=100, verbose_name='\u544a\u8b66\u7ec4')),
                ('comment', models.CharField(max_length=1000, verbose_name='\u8bf4\u660e')),
            ],
            options={
                'db_table': 'alarm_url',
            },
        ),
    ]
