# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-03-06 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('scrape_interval', models.CharField(max_length=100, verbose_name='\u6570\u636e\u83b7\u53d6\u65f6\u95f4\u95f4\u9694')),
                ('scheme', models.CharField(max_length=100, verbose_name='\u63a5\u53e3\u65b9\u5f0fhttp\u6216https')),
                ('insecure_skip_verify', models.CharField(max_length=100, verbose_name='\u5ffd\u7565https\u8bc1\u4e66\u9a8c\u8bc1')),
                ('metrics_path', models.CharField(max_length=100, verbose_name='\u63a5\u53e3uri')),
                ('match', models.CharField(max_length=1000, verbose_name='\u5339\u914d')),
            ],
            options={
                'db_table': 'groupconfig',
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('hid', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('instance', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('groupid', models.CharField(max_length=100)),
                ('monitortype', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=1000, verbose_name='\u6807\u7b7e')),
            ],
            options={
                'db_table': 'hostconfig',
            },
        ),
        migrations.CreateModel(
            name='PrometheusConfig',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='prometheus\u540d\u79f0')),
                ('scrape_interval', models.CharField(max_length=100, verbose_name='\u6570\u636e\u83b7\u53d6\u65f6\u95f4\u95f4\u9694')),
                ('evaluation_interval', models.CharField(max_length=100, verbose_name='\u8ba1\u7b97rule\u7684\u95f4\u9694')),
                ('scrape_timeout', models.CharField(max_length=100, verbose_name='\u8d85\u65f6\u65f6\u95f4')),
                ('alertmanagers_targets', models.CharField(max_length=100, verbose_name='alertmanager\u5730\u5740')),
                ('rule_files_path', models.CharField(max_length=100, verbose_name='\u544a\u8b66\u89c4\u5219\u6587\u4ef6\u8def\u5f84')),
                ('job_path', models.CharField(max_length=100, verbose_name='job\u6587\u4ef6\u8def\u5f84')),
            ],
            options={
                'db_table': 'prometheus_config',
            },
        ),
    ]
