# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-03-26 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addconfig', '0002_auto_20190313_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='instance',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
