# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-03-27 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrometheusPing',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='\u540d\u79f0')),
                ('interval', models.CharField(max_length=100, verbose_name='\u65f6\u95f4\u95f4\u9694')),
                ('uri', models.CharField(max_length=100, verbose_name='uri')),
                ('url', models.CharField(max_length=100, verbose_name='\u5730\u5740')),
            ],
            options={
                'db_table': 'ping_config',
            },
        ),
    ]
